name: Build & Test (RHEL/CentOS)
description: "Composite action to build and test the ODBC connector on RHEL/CentOS"

runs:
  using: "composite"
  steps:
    - name: Set up dependencies
      shell: bash
      run: |
        # Install EPEL repository for additional packages
        dnf install -y epel-release
        dnf config-manager --set-enabled crb -y

        # Update package lists
        dnf update -y

        # Install build dependencies
        dnf groupinstall -y "Development Tools"
        dnf install -y cmake gcc gcc-c++ glib2-devel libsecret-devel krb5-devel unixODBC unixODBC-devel openssl-devel git which docker

    - name: Start S2MS cluster
      shell: bash
      run: |
        python3 -m venv .venv
        source .venv/bin/activate
        python -m pip install singlestoredb
        python ./.github/scripts/setup_s2ms_cluster.py start odbc_test
    - name: Build project
      shell: bash
      run: ./.github/scripts/build-linux-in-docker.sh
    - name: Run tests
      shell: bash
      if: env.NEED_RUN_TESTS != 'false'
      run: ./.github/scripts/run-tests-linux.sh
    # - name: Run browser auth tests  TODO: PLAT-7389 enable these tests
    #   run: ./test/odbc_browser_auth
    - name: Terminate S2MS cluster
      shell: bash
      if: always()
      run: |
          source .venv/bin/activate
          python -m pip install singlestoredb
          python ./.github/scripts/setup_s2ms_cluster.py terminate || true
