name: Run tests for a commit

on:
  push:
    branches: ["**"]

env:
  S2MS_API_KEY: ${{ secrets.S2MS_API_KEY }}
  SINGLESTORE_LICENSE: ${{ secrets.SINGLESTORE_LICENSE }}
  MEMSQL_PASSWORD: ${{ secrets.SINGLESTORE_PASSWORD }}
