name: Publish artifacts (after running the tests)

on:
  push:
    tags:
      - "v*"
  pull_request:
    branches:
      - master

env:
  S2MS_API_KEY: ${{ secrets.S2MS_API_KEY }}
  SINGLESTORE_LICENSE: ${{ secrets.SINGLESTORE_LICENSE }}
  MEMSQL_PASSWORD: ${{ secrets.SINGLESTORE_PASSWORD }}

jobs:
  build-test-linux:
    name: Build & Test (Linux)
    runs-on: ubuntu-latest
    strategy:
      matrix:
        build_type: [RelWithDebInfo]
        driver_type: [unicode, ansi]
        include:
          - build_type: RelWithDebInfo
            driver_type: unicode
            test_dsn: ssodbc_test_w
            test_driver: 'SingleStore ODBC Unicode Driver'
          - build_type: RelWithDebInfo
            driver_type: ansi
            test_dsn: ssodbc_test_a
            test_driver: 'SingleStore ODBC ANSI Driver'
    env:
      BUILD_TYPE: ${{ matrix.build_type }}
      TEST_DSN: ${{ matrix.test_dsn }}
      TEST_DRIVER: ${{ matrix.test_driver }}
      MEMSQL_PORT: 5506
      MEMSQL_USER: root
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Run build and test on Linux (Ubuntu)
        uses: ./.github/workflows/actions/build_test_linux
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: singlestore-odbc-${{ matrix.driver_type }}-linux
          path: |
            build/*.so
            build/libssodbca.so
            build/libssodbcw.so
          retention-days: 30

  build-macos:
    name: Build & Test (macOS)
    runs-on: macos-latest
    strategy:
      matrix:
        build_type: [RelWithDebInfo]
        driver_type: [unicode, ansi]
        include:
          - build_type: RelWithDebInfo
            driver_type: unicode
            test_dsn: ssodbc_test_w
            test_driver: 'SingleStore ODBC Unicode Driver'
          - build_type: RelWithDebInfo
            driver_type: ansi
            test_dsn: ssodbc_test_a
            test_driver: 'SingleStore ODBC ANSI Driver'
    env:
      BUILD_TYPE: ${{ matrix.build_type }}
      TEST_DSN: ${{ matrix.test_dsn }}
      TEST_DRIVER: ${{ matrix.test_driver }}
      DRIVER_TYPE: ${{ matrix.driver_type }}
      MEMSQL_PORT: 3306
      MEMSQL_USER: admin

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Run build and test on MacOS
        uses: ./.github/workflows/actions/build_test_macos
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: singlestore-odbc-${{ matrix.driver_type }}-macos
          path: |
            build/*.dylib
            build/libssodbca.dylib
            build/libssodbcw.dylib
          retention-days: 30

  build-test-windows:
    name: Build & Test (Windows)
    runs-on: windows-latest
    strategy:
      matrix:
        build_type: [RelWithDebInfo]
        driver_type: [unicode, ansi]
        arch_bits: [64]
        include:
          - build_type: RelWithDebInfo
            driver_type: unicode
            arch_bits: 64
            test_dsn: ssodbc_test_w
            test_driver: 'SingleStore ODBC Unicode Driver'
          - build_type: RelWithDebInfo
            driver_type: ansi
            arch_bits: 64
            test_dsn: ssodbc_test_a
            test_driver: 'SingleStore ODBC ANSI Driver'
    env:
      BUILD_TYPE: ${{ matrix.build_type }}
      TEST_DSN: ${{ matrix.test_dsn }}
      TEST_DRIVER: ${{ matrix.test_driver }}
      DRIVER_TYPE: ${{ matrix.driver_type }}
      ARCH_BITS: ${{ matrix.arch_bits }}
      MEMSQL_PORT: 3306
      MEMSQL_USER: admin
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Run build and test on Windows
        uses: ./.github/workflows/actions/build_test_windows
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: singlestore-odbc-${{ matrix.driver_type }}-windows-${{ matrix.arch_bits }}bit
          path: |
            build/*.dll
            build/Release/*.dll
            build/Debug/*.dll
          retention-days: 30
