name: Publish installers

on:
  push:
    tags:
      - "v*"
  pull_request:
    branches:
      - master

env:
  S2MS_API_KEY: ${{ secrets.S2MS_API_KEY }}
  SINGLESTORE_LICENSE: ${{ secrets.SINGLESTORE_LICENSE }}
  MEMSQL_PASSWORD: ${{ secrets.SINGLESTORE_PASSWORD }}
  DRIVER_VERSION: 1.2.0

jobs:
  # build-test-ubuntu:
  #   name: Build & Test (Ubuntu)
  #   strategy:
  #     fail-fast: false
  #     matrix:
  #       build_type: [RelWithDebInfo]
  #       driver_type: [unicode, ansi]
  #       os_name: [ubuntu]
  #       include:
  #         - build_type: RelWithDebInfo
  #           driver_type: unicode
  #           test_dsn: ssodbc_test_w
  #           test_driver: 'SingleStore ODBC Unicode Driver'
  #           arch: amd64
  #           image: ubuntu-24.04
  #         - build_type: RelWithDebInfo
  #           driver_type: ansi
  #           test_dsn: ssodbc_test_a
  #           test_driver: 'SingleStore ODBC ANSI Driver'
  #           arch: amd64  # TODO: change to arm64 when arm64 dev image is released
  #           image: ubuntu-22.04
  #   runs-on: ${{ matrix.image }}
  #   env:
  #     BUILD_TYPE: ${{ matrix.build_type }}
  #     TEST_DSN: ${{ matrix.test_dsn }}
  #     TEST_DRIVER: ${{ matrix.test_driver }}
  #     MEMSQL_PORT: 5506
  #     MEMSQL_USER: root
  #   steps:
  #     - name: Checkout code
  #       uses: actions/checkout@v4
  #     - name: Run build and test on Linux (Ubuntu)
  #       uses: ./.github/workflows/actions/build_test_linux
  #     - name: Create archive
  #       run: |
  #           mkdir singlestore-connector-odbc-${{ env.DRIVER_VERSION }}-${{ matrix.os_name }}-${{ matrix.arch }}
  #           mkdir singlestore-connector-odbc-${{ env.DRIVER_VERSION }}-${{ matrix.os_name }}-${{ matrix.arch }}/plugins
  #           cp linuxinstall/README.md singlestore-connector-odbc-${{ env.DRIVER_VERSION }}-${{ matrix.os_name }}-${{ matrix.arch }}
  #           cp libssodbca.so singlestore-connector-odbc-${{ env.DRIVER_VERSION }}-${{ matrix.os_name }}-${{ matrix.arch }}
  #           cp libssodbcw.so singlestore-connector-odbc-${{ env.DRIVER_VERSION }}-${{ matrix.os_name }}-${{ matrix.arch }}
  #           cp libmariadb/auth_gssapi_client.so singlestore-connector-odbc-${{ env.DRIVER_VERSION }}-${{ matrix.os_name }}-${{ matrix.arch }}/plugins
  #           tar -zcvf singlestore-connector-odbc-${{ env.DRIVER_VERSION }}-${{ matrix.os_name }}-${{ matrix.arch }}.tar.gz singlestore-connector-odbc-${{ env.DRIVER_VERSION }}-${{ matrix.os_name }}-${{ matrix.arch }}
  #     - name: Upload artifacts
  #       if: matrix.driver_type == 'unicode'
  #       uses: actions/upload-artifact@v4
  #       with:
  #         name: singlestore-odbc-${{ matrix.driver_type }}-${{ matrix.os_name }}
  #         path: singlestore-connector-odbc-${{ env.DRIVER_VERSION }}-${{ matrix.os_name }}-${{ matrix.arch }}.tar.gz
  #         retention-days: 30

  build-test-centos:
    name: Build & Test (RHEL/CentOS)
    runs-on: ubuntu-latest
    container: 
      image: quay.io/centos/centos:stream9
    strategy:
      matrix:
        build_type: [RelWithDebInfo]
        driver_type: [unicode, ansi]
        os_name: [centos]
        include:
          - build_type: RelWithDebInfo
            driver_type: unicode
            test_dsn: ssodbc_test_w
            test_driver: 'SingleStore ODBC Unicode Driver'
          - build_type: RelWithDebInfo
            driver_type: ansi
            test_dsn: ssodbc_test_a
            test_driver: 'SingleStore ODBC ANSI Driver'
    env:
      BUILD_TYPE: ${{ matrix.build_type }}
      TEST_DSN: ${{ matrix.test_dsn }}
      TEST_DRIVER: ${{ matrix.test_driver }}
      DRIVER_TYPE: ${{ matrix.driver_type }}
      MEMSQL_PORT: 3306
      MEMSQL_USER: admin
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Run build and test on RHEL/CentOS
        uses: ./.github/workflows/actions/build_test_centos
      - name: Create archive
        run: |
            mkdir singlestore-connector-odbc-${{ env.DRIVER_VERSION }}-${{ matrix.os_name }}-amd64
            mkdir singlestore-connector-odbc-${{ env.DRIVER_VERSION }}-${{ matrix.os_name }}-amd64/plugins
            cp linuxinstall/README.md singlestore-connector-odbc-${{ env.DRIVER_VERSION }}-${{ matrix.os_name }}-amd64
            cp build/libssodbca.so singlestore-connector-odbc-${{ env.DRIVER_VERSION }}-${{ matrix.os_name }}-amd64
            cp build/libssodbcw.so singlestore-connector-odbc-${{ env.DRIVER_VERSION }}-${{ matrix.os_name }}-amd64
            cp build/libmariadb/auth_gssapi_client.so singlestore-connector-odbc-${{ env.DRIVER_VERSION }}-${{ matrix.os_name }}-amd64/plugins
            tar -zcvf singlestore-connector-odbc-${{ env.DRIVER_VERSION }}-${{ matrix.os_name }}-amd64.tar.gz singlestore-connector-odbc-${{ env.DRIVER_VERSION }}-${{ matrix.os_name }}-amd64
      - name: Upload artifacts
        if: matrix.driver_type == 'unicode'
        uses: actions/upload-artifact@v4
        with:
          name: singlestore-odbc-${{ matrix.driver_type }}-${{ matrix.os_name }}
          path: singlestore-connector-odbc-${{ env.DRIVER_VERSION }}-${{ matrix.os_name }}-amd64.tar.gz
          retention-days: 30

  # build-test-macos:
  #   name: Build & Test (macOS)
  #   strategy:
  #     fail-fast: false
  #     matrix:
  #       build_type: [RelWithDebInfo]
  #       driver_type: [unicode]
  #       arch: [x86_64]
  #       include:
  #         - build_type: RelWithDebInfo
  #           driver_type: unicode
  #           test_dsn: ssodbc_test_w
  #           test_driver: 'SingleStore ODBC Unicode Driver'
  #           arch: x86_64
  #           image_arch: intel
  #         - build_type: RelWithDebInfo
  #           driver_type: ansi
  #           test_dsn: ssodbc_test_a
  #           test_driver: 'SingleStore ODBC ANSI Driver'
  #           arch: x86_64
  #           image_arch: intel

  #   runs-on: macos-15-${{ matrix.image_arch }}
  #   env:
  #     BUILD_TYPE: ${{ matrix.build_type }}
  #     TEST_DSN: ${{ matrix.test_dsn }}
  #     TEST_DRIVER: ${{ matrix.test_driver }}
  #     DRIVER_TYPE: ${{ matrix.driver_type }}
  #     MEMSQL_PORT: 3306
  #     MEMSQL_USER: admin

  #   steps:
  #     - name: Checkout code
  #       uses: actions/checkout@v4
  #     - name: Run build and test on MacOS
  #       uses: ./.github/workflows/actions/build_test_macos
  #     - name: Upload artifacts
  #       if: matrix.driver_type == 'unicode'
  #       uses: actions/upload-artifact@v4
  #       with:
  #         name: singlestore-odbc-${{ matrix.driver_type }}-macos
  #         path: osxinstall/singlestore-connector-odbc-${{ env.DRIVER_VERSION }}-macos-${{ matrix.arch }}.pkg
  #         retention-days: 30

  # build-test-windows:
  #   name: Build & Test (Windows)
  #   runs-on: windows-latest
  #   strategy:
  #     fail-fast: false
  #     matrix:
  #       build_type: [RelWithDebInfo]
  #       driver_type: [unicode]
  #       arch_bits: [64]
  #       include:
  #         - build_type: RelWithDebInfo
  #           driver_type: unicode
  #           arch_bits: 64
  #           test_dsn: ssodbc_test_w
  #           test_driver: 'SingleStore ODBC Unicode Driver'
  #         - build_type: RelWithDebInfo
  #           driver_type: ansi
  #           arch_bits: 32
  #           test_dsn: ssodbc_test_a
  #           test_driver: 'SingleStore ODBC ANSI Driver'
  #   env:
  #     BUILD_TYPE: ${{ matrix.build_type }}
  #     TEST_DSN: ${{ matrix.test_dsn }}
  #     TEST_DRIVER: ${{ matrix.test_driver }}
  #     DRIVER_TYPE: ${{ matrix.driver_type }}
  #     ARCH_BITS: ${{ matrix.arch_bits }}
  #     MEMSQL_PORT: 3306
  #     MEMSQL_USER: admin
  #   steps:
  #     - name: Checkout code
  #       uses: actions/checkout@v4
  #     - name: Run build and test on Windows
  #       uses: ./.github/workflows/actions/build_test_windows
  #     - name: Upload artifacts
  #       uses: actions/upload-artifact@v4
  #       with:
  #         name: singlestore-odbc-${{ matrix.driver_type }}-windows-${{ matrix.arch_bits }}bit
  #         path: wininstall\singlestore-connector-odbc-${{ env.DRIVER_VERSION }}-win${{ matrix.arch_bits }}.msi
  #         retention-days: 30

  # create-draft-release:
  #   name: Create Draft Release
  #   runs-on: ubuntu-latest
  #   # if: startsWith(github.ref, 'refs/tags/v')
  #   needs: [build-test-ubuntu, build-test-centos, build-test-macos, build-test-windows]
  #   steps:
  #     - name: Checkout code
  #       uses: actions/checkout@v4
      
  #     - name: Download all artifacts
  #       uses: actions/download-artifact@v4
  #       with:
  #         path: artifacts
      
  #     - name: Create Draft Release with Assets
  #       uses: softprops/action-gh-release@v2
  #       with:
  #         name: SingleStore ODBC Connector ${{ github.ref_name }}
  #         body: |
  #           ## SingleStore ODBC Connector ${{ github.ref_name }}
            
  #           This is a draft release for the SingleStore ODBC Connector.
            
  #           ### Downloads
  #           - **Linux (Ubuntu)**: `singlestore-connector-odbc-${{ env.DRIVER_VERSION }}-ubuntu-*.tar.gz`
  #           - **Linux (CentOS/RHEL)**: `singlestore-connector-odbc-${{ env.DRIVER_VERSION }}-centos-*.tar.gz`
  #           - **macOS**: `singlestore-connector-odbc-${{ env.DRIVER_VERSION }}-macos-*.pkg`
  #           - **Windows**: `singlestore-connector-odbc-${{ env.DRIVER_VERSION }}-win*.msi`
            
  #           ### Installation Instructions
  #           Please refer to the README.md file included in each package for installation instructions.
  #         draft: true
  #         prerelease: false
  #         generate_release_notes: true
  #         files: |
  #           artifacts/singlestore-odbc-unicode-ubuntu/singlestore-connector-odbc-${{ env.DRIVER_VERSION }}-ubuntu-amd64.tar.gz
  #           artifacts/singlestore-odbc-unicode-centos/singlestore-connector-odbc-${{ env.DRIVER_VERSION }}-centos-amd64.tar.gz
  #           artifacts/singlestore-odbc-unicode-macos/singlestore-connector-odbc-${{ env.DRIVER_VERSION }}-macos-x86_64.pkg
  #           artifacts/singlestore-odbc-unicode-windows-64bit/singlestore-connector-odbc-${{ env.DRIVER_VERSION }}-win64.msi
  #           artifacts/singlestore-odbc-ansi-windows-32bit/singlestore-connector-odbc-${{ env.DRIVER_VERSION }}-win32.msi
